#!/bin/sh
# No need to get GO111MODULE to on anymore (1.17+)
go get sigs.k8s.io/kind
echo 'Add the following to your .bashrc (or equivalent):

  source <(kind completion bash)

Note that this used the kubernetes submodule. '
